baseURL = "https://zak-yyj.github.io/"
languageCode = "en"
title = "Yijie Yang"
theme = "PaperMod"

[params]
  author = "Yijie Yang"
  description = "MSc in Surveying and Mapping | Cartography & Remote Sensing"
  defaultTheme = "light"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv/"
    weight = 20

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 30

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 40
